# Form implementation generated from reading ui file '/home/cedric-oswald-syeni/Documents/QtDesignStudio/Projects/motion_sensor/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 0, 221, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 30, 61, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.toolButton_4 = QtWidgets.QToolButton(parent=self.frame_2)
        self.toolButton_4.setGeometry(QtCore.QRect(5, 0, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.toolButton_4.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/cedric-oswald-syeni/Documents/QtDesignStudio/Projects/motion_sensor/assets/graph.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(61, 30, 101, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.toolButton_5 = QtWidgets.QToolButton(parent=self.frame_3)
        self.toolButton_5.setGeometry(QtCore.QRect(4, 0, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.toolButton_5.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/cedric-oswald-syeni/Documents/QtDesignStudio/Projects/motion_sensor/assets/performance.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_5.setObjectName("toolButton_5")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setGeometry(QtCore.QRect(163, 31, 61, 61))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.toolButton_6 = QtWidgets.QToolButton(parent=self.frame_4)
        self.toolButton_6.setGeometry(QtCore.QRect(2, -1, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.toolButton_6.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/cedric-oswald-syeni/Documents/QtDesignStudio/Projects/motion_sensor/assets/status.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_6.setIcon(icon2)
        self.toolButton_6.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_6.setObjectName("toolButton_6")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setGeometry(QtCore.QRect(59, 100, 101, 111))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(parent=self.frame_5)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/cedric-oswald-syeni/Documents/QtDesignStudio/Projects/motion_sensor/assets/light_on.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame)
        self.frame_6.setGeometry(QtCore.QRect(59, 210, 101, 31))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 66, 18))
        self.label_2.setObjectName("label_2")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame)
        self.frame_8.setGeometry(QtCore.QRect(50, 4, 110, 16))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 0, 231, 271))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_7 = QtWidgets.QFrame(parent=self.gridLayoutWidget_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_9.setGeometry(QtCore.QRect(40, 60, 141, 21))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(14, 8, 179);")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_10.setGeometry(QtCore.QRect(10, 100, 91, 61))
        self.frame_10.setStyleSheet("border: 1px solid #ddd;\n"
"border-radius: 8px;\n"
"background: white;\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 66, 18))
        self.label_5.setStyleSheet("border: 0;\n"
"color: rgb(87, 58, 171);\n"
"font-weight: bold;\n"
"text-decoration: underline;\n"
"\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_9.setGeometry(QtCore.QRect(10, 37, 66, 18))
        self.label_9.setStyleSheet("color: green;\n"
"border: 0;\n"
"font-weight: bold,")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_11.setGeometry(QtCore.QRect(10, 170, 91, 61))
        self.frame_11.setStyleSheet("border: 1px solid #ddd;\n"
"border-radius: 8px;\n"
"background: white;\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_7.setGeometry(QtCore.QRect(11, 9, 66, 18))
        self.label_7.setStyleSheet("border: 0;\n"
"color: rgb(87, 58, 171);\n"
"font-weight: bold;\n"
"text-decoration: underline;\n"
"\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_11.setGeometry(QtCore.QRect(10, 37, 66, 18))
        self.label_11.setStyleSheet("color: green;\n"
"border: 0;\n"
"font-weight: bold,")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_12.setGeometry(QtCore.QRect(120, 100, 91, 61))
        self.frame_12.setStyleSheet("border: 1px solid #ddd;\n"
"border-radius: 8px;\n"
"background: white;\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_6.setGeometry(QtCore.QRect(11, 10, 66, 18))
        self.label_6.setStyleSheet("border: 0;\n"
"color: rgb(87, 58, 171);\n"
"font-weight: bold;\n"
"text-decoration: underline;\n"
"\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_10.setGeometry(QtCore.QRect(12, 38, 66, 18))
        self.label_10.setStyleSheet("color: red;\n"
"border: 0;\n"
"font-weight: bold,")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_13.setGeometry(QtCore.QRect(120, 170, 91, 61))
        self.frame_13.setStyleSheet("border: 1px solid #ddd;\n"
"border-radius: 8px;\n"
"background: white;\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_8.setGeometry(QtCore.QRect(11, 10, 66, 18))
        self.label_8.setStyleSheet("border: 0;\n"
"color: rgb(87, 58, 171);\n"
"font-weight: bold;\n"
"text-decoration: underline;\n"
"\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_12.setGeometry(QtCore.QRect(12, 33, 66, 18))
        self.label_12.setStyleSheet("color: green;\n"
"border: 0;\n"
"font-weight: bold,")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.frame_7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_4.setText(_translate("MainWindow", "Plot"))
        self.toolButton_5.setText(_translate("MainWindow", "Performance"))
        self.toolButton_6.setText(_translate("MainWindow", "Status"))
        self.label_2.setText(_translate("MainWindow", "Light On"))
        self.label_3.setText(_translate("MainWindow", "29/05/2025  10:30"))
        self.label_4.setText(_translate("MainWindow", "PERFORMANCE"))
        self.label_5.setText(_translate("MainWindow", "RAM"))
        self.label_9.setText(_translate("MainWindow", "20%"))
        self.label_7.setText(_translate("MainWindow", "Memory"))
        self.label_11.setText(_translate("MainWindow", "30%"))
        self.label_6.setText(_translate("MainWindow", "CPU"))
        self.label_10.setText(_translate("MainWindow", "98%"))
        self.label_8.setText(_translate("MainWindow", "Network"))
        self.label_12.setText(_translate("MainWindow", "50kbs"))
